import RootLayout from '@/components/RootLayout/RootLayout';
import './globals.css';

export const metadata = {
	title: 'JOSN Docs',
	description: 'Generated by create next app',
};

export default RootLayout;
